name: "Update PR body"
description: "Update PR body because PR comments are annoying :)"
inputs:
  body:
    description: "body"
    required: true
  GITHUB_TOKEN:
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "link"
  color: "blue"
